import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: '01. Overview',
      collapsed: false,
      items: [
        'overview/introduction',
        'overview/product-overview',
        'overview/core-concepts',
        'overview/terminology',
      ],
    },
    {
      type: 'category',
      label: '02. Getting Started',
      collapsed: false,
      items: [
        'getting-started/prerequisites',
        'getting-started/installation',
        'getting-started/local-development',
        'getting-started/environment-variables',
        'getting-started/first-run',
      ],
    },
    {
      type: 'category',
      label: '03. Architecture',
      collapsed: true,
      items: [
        'architecture/system-architecture',
        'architecture/architecture-principles',
        'architecture/request-flow',
        'architecture/data-flow',
        'architecture/frontend-architecture',
        'architecture/backend-architecture',
        'architecture/database-architecture',
        'architecture/ai-architecture',
      ],
    },
    {
      type: 'category',
      label: '04. Frontend',
      collapsed: true,
      items: [
        'frontend/overview',
        'frontend/routing',
        'frontend/state-management',
        'frontend/components',
        'frontend/design-system',
        'frontend/geospatial-ui',
        'frontend/responsive-design',
        'frontend/accessibility',
      ],
    },
    {
      type: 'category',
      label: '05. Backend',
      collapsed: true,
      items: [
        'backend/overview',
        'backend/api-architecture',
        'backend/middleware',
        'backend/services',
        'backend/workflows',
        'backend/error-handling',
        'backend/background-processing',
      ],
    },
    {
      type: 'category',
      label: '06. Database',
      collapsed: true,
      items: [
        'database/overview',
        'database/schema',
        'database/relationships',
        'database/migrations',
        'database/indexing',
        'database/transactions',
        'database/concurrency',
      ],
    },
    {
      type: 'category',
      label: '07. Authentication & Authorization',
      collapsed: true,
      items: [
        'authentication/authentication',
        'authentication/sessions',
        'authentication/authorization',
        'authentication/roles',
        'authentication/permissions',
        'authentication/security-model',
      ],
    },
    {
      type: 'category',
      label: '08. Domain Operations',
      collapsed: true,
      items: [
        'domain/incident-management',
        'domain/case-management',
        'domain/case-lifecycle',
        'domain/task-management',
        'domain/priority-engine',
        'domain/evidence-management',
        'domain/outcomes',
        'domain/audit-trail',
      ],
    },
    {
      type: 'category',
      label: '09. Geospatial & GIS',
      collapsed: true,
      items: [
        'geospatial/overview',
        'geospatial/map-architecture',
        'geospatial/geojson',
        'geospatial/layers',
        'geospatial/coordinates',
        'geospatial/spatial-data',
        'geospatial/map-interactions',
        'geospatial/external-data',
      ],
    },
    {
      type: 'category',
      label: '10. Offline & Sync Engine',
      collapsed: true,
      items: [
        'offline/pwa',
        'offline/offline-architecture',
        'offline/indexeddb',
        'offline/sync-engine',
        'offline/conflict-resolution',
        'offline/retry-strategy',
      ],
    },
    {
      type: 'category',
      label: '11. AI / ML Intelligence',
      collapsed: true,
      items: [
        'ai-ml/overview',
        'ai-ml/model-architecture',
        'ai-ml/damage-assessment',
        'ai-ml/model-providers',
        'ai-ml/inference-flow',
        'ai-ml/confidence',
        'ai-ml/priority-vs-confidence',
        'ai-ml/future-ml-integration',
      ],
    },
    {
      type: 'category',
      label: '12. API Reference',
      collapsed: true,
      items: [
        'api/overview',
        'api/authentication',
        'api/incidents',
        'api/cases',
        'api/tasks',
        'api/evidence',
        'api/field-observations',
        'api/analytics',
        'api/audit',
        'api/demo',
        'api/errors',
      ],
    },
    {
      type: 'category',
      label: '13. Testing Strategy',
      collapsed: true,
      items: [
        'testing/testing-strategy',
        'testing/unit-tests',
        'testing/integration-tests',
        'testing/end-to-end-tests',
        'testing/api-tests',
        'testing/security-tests',
        'testing/offline-tests',
        'testing/test-data',
      ],
    },
    {
      type: 'category',
      label: '14. Security & Hardening',
      collapsed: true,
      items: [
        'security/security-overview',
        'security/authentication-security',
        'security/authorization-security',
        'security/file-upload-security',
        'security/input-validation',
        'security/data-protection',
        'security/ai-security',
        'security/auditability',
        'security/threat-model',
      ],
    },
    {
      type: 'category',
      label: '15. Deployment & DevOps',
      collapsed: true,
      items: [
        'deployment/local',
        'deployment/docker',
        'deployment/replit',
        'deployment/production',
        'deployment/database-deployment',
        'deployment/environment-management',
        'deployment/backups',
        'deployment/monitoring',
      ],
    },
    {
      type: 'category',
      label: '16. Maintenance & Runbooks',
      collapsed: true,
      items: [
        'maintenance/troubleshooting',
        'maintenance/debugging',
        'maintenance/logging',
        'maintenance/common-errors',
        'maintenance/dependency-updates',
        'maintenance/database-recovery',
      ],
    },
    {
      type: 'category',
      label: '17. Contributing & Development',
      collapsed: true,
      items: [
        'contributing/development-workflow',
        'contributing/code-style',
        'contributing/branching',
        'contributing/pull-requests',
        'contributing/commit-conventions',
        'contributing/adding-features',
      ],
    },
    {
      type: 'category',
      label: '18. Technical Reference',
      collapsed: true,
      items: [
        'reference/configuration',
        'reference/environment-reference',
        'reference/api-reference',
        'reference/data-model-reference',
        'reference/status-reference',
        'reference/permissions-reference',
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: '19. Roadmap & Technical Debt',
      collapsed: true,
      items: [
        'roadmap/current-state',
        'roadmap/technical-debt',
        'roadmap/planned-improvements',
        'roadmap/future-architecture',
      ],
    },
  ],
};

export default sidebars;
