import fs from 'fs';
import path from 'path';

export function generateData(DOCS_DIR) {
  const write = (relPath, content) => {
    const fullPath = path.join(DOCS_DIR, relPath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, content.trim() + '\n', 'utf8');
  };

  write('06-database/schema.md', [
    '# Database Schema',
    '',
    '<span className="badge-implemented">Implemented</span>',
    '',
    '## Overview',
    'The DRAXELYRA platform utilizes PostgreSQL as its primary datastore, leveraging **Drizzle ORM** for schema definition and migrations. The schema encompasses 15 tables that form the foundation for tracking users, incidents, detections, and case lifecycles.',
    '',
    'Source file: `lib/db/src/schema/index.ts`',
    '',
    '## Tables',
    '',
    '### 1. `users`',
    '- **id**: `text` (PK)',
    '- **name**: `text`',
    '- **email**: `text` (unique)',
    '- **passwordHash**: `text`',
    '- **role**: `text`',
    '- **organizationId**: `text`',
    '- **createdAt**: `timestamp`',
    '',
    '### 2. `organizations`',
    '- **id**: `text` (PK)',
    '- **name**: `text`',
    '- **type**: `text`',
    '',
    '### 3. `incidents`',
    '- **id**: `text` (PK)',
    '- **name**: `text`',
    '- **disasterType**: `text`',
    '- **status**: `text`',
    '- **startTime**: `timestamp`',
    '- **endTime**: `timestamp`',
    '- **aoi**: `jsonb` (GeoJSON)',
    '- **source**: `text`',
    '- **description**: `text`',
    '- **severity**: `text`',
    '- **createdBy**: `text` (FK `users`)',
    '- **createdAt**: `timestamp`',
    '- **updatedAt**: `timestamp`',
    '',
    '### 4. `imageryAssets`',
    '- **id**: `text` (PK)',
    '- **incidentId**: `text` (FK `incidents`)',
    '- **filename**: `text`',
    '- **source**: `text`',
    '- **acquisitionTime**: `timestamp`',
    '- **captureType**: `text`',
    '- **geometry**: `jsonb`',
    '- **qualityStatus**: `text`',
    '- **storagePath**: `text`',
    '- **metadata**: `jsonb`',
    '- **processingStatus**: `text`',
    '',
    '### 5. `criticalAssets`',
    '- **id**: `text` (PK)',
    '- **name**: `text`',
    '- **type**: `text`',
    '- **location**: `jsonb` (`{lat, lng}`)',
    '- **criticalityScore**: `number`',
    '- **populationExposureTier**: `text`',
    '',
    '### 6. `detections`',
    '- **id**: `text` (PK)',
    '- **incidentId**: `text` (FK `incidents`)',
    '- **imageryId**: `text` (FK `imageryAssets`)',
    '- **geometry**: `jsonb`',
    '- **class**: `text`',
    '- **severity**: `text`',
    '- **confidence**: `doublePrecision`',
    '- **modelName**: `text`',
    '- **modelVersion**: `text`',
    '- **inferenceTimestamp**: `timestamp`',
    '',
    '### 7. `cases`',
    '- **id**: `text` (PK)',
    '- **incidentId**: `text` (FK `incidents`)',
    '- **detectionId**: `text` (FK `detections`)',
    '- **assetId**: `text` (FK `criticalAssets`)',
    '- **status**: `text`',
    '- **priorityScore**: `doublePrecision`',
    '- **priorityBreakdown**: `jsonb`',
    '- **reviewState**: `text`',
    '- **owner**: `text` (FK `users`)',
    '- **version**: `int` (default 1)',
    '- **createdAt**: `timestamp`',
    '- **updatedAt**: `timestamp`',
    '',
    '### 8. `evidence`',
    '- **id**: `text` (PK)',
    '- **caseId**: `text` (FK `cases`)',
    '- **type**: `text`',
    '- **uri**: `text`',
    '- **source**: `text`',
    '- **mimeType**: `text`',
    '- **size**: `int`',
    '- **checksum**: `text` (SHA-256)',
    '- **metadata**: `jsonb`',
    '- **createdBy**: `text` (FK `users`)',
    '- **timestamp**: `timestamp`',
    '',
    '### 9. `reviews`',
    '- **id**: `text` (PK)',
    '- **caseId**: `text` (FK `cases`)',
    '- **reviewer**: `text` (FK `users`)',
    '- **decision**: `text`',
    '- **reason**: `text`',
    '- **notes**: `text`',
    '- **createdAt**: `timestamp`',
    '',
    '### 10. `tasks`',
    '- **id**: `text` (PK)',
    '- **caseId**: `text` (FK `cases`)',
    '- **title**: `text`',
    '- **description**: `text`',
    '- **priority**: `int`',
    '- **assignedTeam**: `text`',
    '- **assignedUser**: `text` (FK `users`)',
    '- **status**: `text`',
    '- **version**: `int` (default 1)',
    '- **createdAt**: `timestamp`',
    '- **dueAt**: `timestamp`',
    '- **escalationAt**: `timestamp`',
    '- **completedAt**: `timestamp`',
    '',
    '### 11. `fieldObservations`',
    '- **id**: `text` (PK)',
    '- **caseId**: `text` (FK `cases`)',
    '- **taskId**: `text` (FK `tasks`)',
    '- **location**: `jsonb`',
    '- **media**: `jsonb`',
    '- **notes**: `text`',
    '- **verificationStatus**: `text`',
    '- **syncStatus**: `text`',
    '- **version**: `int` (default 1)',
    '- **createdAt**: `timestamp`',
    '',
    '### 12. `outcomes`',
    '- **id**: `text` (PK)',
    '- **caseId**: `text` (FK `cases`)',
    '- **action**: `text`',
    '- **result**: `text`',
    '- **evidence**: `jsonb`',
    '- **completedBy**: `text` (FK `users`)',
    '- **completedAt**: `timestamp`',
    '',
    '### 13. `caseStatusHistory`',
    '- **id**: `text` (PK)',
    '- **caseId**: `text` (FK `cases`)',
    '- **fromStatus**: `text`',
    '- **toStatus**: `text`',
    '- **user**: `text` (FK `users`)',
    '- **reason**: `text`',
    '- **timestamp**: `timestamp`',
    '',
    '### 14. `auditEvents`',
    '- **id**: `text` (PK)',
    '- **actorId**: `text` (FK `users`)',
    '- **entityType**: `text`',
    '- **entityId**: `text`',
    '- **action**: `text`',
    '- **metadata**: `jsonb`',
    '- **timestamp**: `timestamp`',
    '',
    '### 15. `session`',
    '- **sid**: `varchar` (PK)',
    '- **sess**: `jsonb`',
    '- **expire**: `timestamp`',
    '*(Used for connect-pg-simple)*'
  ].join('\n'));

  write('06-database/architecture.md', [
    '# Database Architecture',
    '',
    '<span className="badge-implemented">Implemented</span>',
    '',
    '## Database Connection',
    'We use `pg.Pool` for connecting to the database and pass the pool to `drizzle` to create the ORM instance.',
    '',
    'Source file: `lib/db/src/index.ts`',
    '```typescript',
    'import { drizzle } from "drizzle-orm/node-postgres";',
    'import pg from "pg";',
    'import * as schema from "./schema";',
    '',
    'const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });',
    'export const db = drizzle(pool, { schema });',
    '```',
    '',
    '## Drizzle ORM usage',
    'Drizzle handles all schema definition, querying, and migrations. Relations between tables are explicitly defined to allow relational queries.',
    'Migrations are generated and applied via the Drizzle CLI.'
  ].join('\n'));

  write('06-database/concurrency.md', [
    '# Database Concurrency',
    '',
    '<span className="badge-implemented">Implemented</span>',
    '',
    '## Optimistic Concurrency Control (OCC)',
    'DRAXELYRA implements OCC using a `version` column on critical tables such as `cases`, `tasks`, and `fieldObservations`.',
    'This prevents lost updates during concurrent edits by multiple operators.',
    '',
    'When a transition is made, the query checks that the current database version matches the expected version:',
    '```sql',
    'UPDATE cases',
    'SET status = $1, version = version + 1',
    'WHERE id = $2 AND version = $3',
    '```',
    '',
    'If 0 rows are affected, the system throws a `VERSION_CONFLICT` error, forcing the client to reload the latest state and retry.',
    '',
    '## Transactions',
    'All state transitions occur within a database transaction. For example:',
    '```typescript',
    'await db.transaction(async (tx) => {',
    '  // 1. Update status and increment version',
    '  // 2. Insert into caseStatusHistory',
    '  // 3. Insert into auditEvents',
    '});',
    '```',
    'This ensures atomicity; if the OCC check fails, the history and audit logs are rolled back.'
  ].join('\n'));

  write('07-authentication/authentication-rbac.md', [
    '# Authentication & RBAC',
    '',
    '<span className="badge-implemented">Implemented</span>',
    '',
    '## Session Management',
    'Authentication is handled via session cookies backed by PostgreSQL using `connect-pg-simple`.',
    '',
    '**Configuration (`app.ts`):**',
    '- **Store**: PostgreSQL `session` table',
    '- **Secret**: `process.env.SESSION_SECRET || "draxelyra_default_secret"`',
    '- **Cookie Options**: `httpOnly: true`, `secure: process.env.NODE_ENV === "production"`, `maxAge: 30 days`',
    '- **Session Settings**: `resave: false`, `saveUninitialized: false`',
    '',
    '## Authentication Routes',
    'Defined in `routes/auth.ts`:',
    '- **POST /login**: Validates credentials, uses `bcrypt.compare`, and sets `req.session.userId` and `req.session.role`.',
    '- **POST /logout**: Requires authentication, calls `req.session.destroy()`.',
    '- **GET /me**: Requires authentication, returns user profile (excluding `passwordHash`).',
    '',
    '## Middleware',
    'Access control is enforced via middleware in `middlewares/auth.ts`:',
    '```typescript',
    '// requireAuth: Checks if req.session.userId exists, otherwise returns 401 UNAUTHORIZED',
    '// requireRole(...roles): Checks authentication, then verifies role, returning 403 FORBIDDEN if unauthorized',
    '```',
    '',
    '## Role Matrix & Demo Users',
    'DRAXELYRA seeds 6 demo users (password: `demo123`):',
    '1. **System Admin** (Sam SysAdmin, admin@draxelyra.local) - ALL endpoints',
    '2. **Organization Admin** (Olivia OrgAdmin, orgadmin@draxelyra.local) - incidents CRUD, cases review, tasks CRUD',
    '3. **Commander** (Cole Commander, commander@draxelyra.local) - incidents CRUD, cases review, tasks CRUD',
    '4. **Disaster Officer** - incidents CRUD, cases review, tasks CRUD',
    '5. **Manager** (Mary Manager, manager@draxelyra.local) - cases review, tasks CRUD',
    '6. **Analyst** (Alice Analyst, analyst@draxelyra.local) - cases review, case audit',
    '7. **Field Responder** (Frank Field, field@draxelyra.local) - tasks PATCH, case audit (read)'
  ].join('\n'));

  write('08-domain/case-lifecycle.md', [
    '# Case Lifecycle',
    '',
    '<span className="badge-implemented">Implemented</span>',
    '',
    '## State Machine',
    'The core domain logic of a case follows a strict state machine implemented in `services/case-state-machine.ts`.',
    '',
    '```mermaid',
    'stateDiagram-v2',
    '  DETECTED --> NEEDS_REVIEW',
    '  NEEDS_REVIEW --> CONFIRMED',
    '  NEEDS_REVIEW --> REJECTED',
    '  NEEDS_REVIEW --> UNCERTAIN',
    '  CONFIRMED --> PRIORITIZED',
    '  CONFIRMED --> TASKED',
    '  PRIORITIZED --> TASKED',
    '  TASKED --> IN_PROGRESS',
    '  IN_PROGRESS --> FIELD_VERIFIED',
    '  IN_PROGRESS --> ACTIONED',
    '  FIELD_VERIFIED --> ACTIONED',
    '  ACTIONED --> CLOSED',
    '  UNCERTAIN --> CLOSED',
    '  REJECTED --> CLOSED',
    '```',
    '',
    '## Transition Logic',
    'Transitions are handled by `transitionCase(caseId, newStatus, userId, expectedVersion, notes?, extraUpdates?)`.',
    'This function:',
    '1. Begins a transaction (`db.transaction()`).',
    '2. Checks `expectedVersion` to enforce OCC. Throws `VERSION_CONFLICT` if mismatched.',
    '3. Validates the transition (e.g., cannot go from `CLOSED` back to `IN_PROGRESS`). Throws `INVALID_TRANSITION` on failure.',
    '4. Updates the case status and increments the version.',
    '5. Inserts an entry into `caseStatusHistory`.',
    '6. Emits an audit event into `auditEvents`.',
    '',
    '## Auto-Transitions',
    '- **Creating a task** automatically transitions a case to `TASKED`.',
    '- **Task verification** automatically transitions a case to `FIELD_VERIFIED`.'
  ].join('\n'));

  write('08-domain/task-evidence-audit.md', [
    '# Tasks, Evidence, and Audit',
    '',
    '<span className="badge-implemented">Implemented</span>',
    '',
    '## Task State Machine',
    'Implemented in `services/task-state-machine.ts`:',
    '```mermaid',
    'stateDiagram-v2',
    '  UNASSIGNED --> ASSIGNED',
    '  ASSIGNED --> IN_PROGRESS',
    '  ASSIGNED --> UNASSIGNED',
    '  IN_PROGRESS --> BLOCKED',
    '  IN_PROGRESS --> COMPLETED',
    '  IN_PROGRESS --> VERIFIED',
    '  BLOCKED --> IN_PROGRESS',
    '  BLOCKED --> UNASSIGNED',
    '  COMPLETED --> VERIFIED',
    '  COMPLETED --> CLOSED',
    '  VERIFIED --> CLOSED',
    '```',
    '',
    '## SLA Calculation',
    'When a task is created (`POST /api/tasks`), SLA is determined by priority:',
    '- Priority >= 75 → 30min',
    '- Priority >= 45 → 2h',
    '- Else → 8h',
    '`escalationAt` is set to `dueAt + 30min`.',
    '',
    '## Evidence Upload Pipeline',
    'Located in `routes/evidence.ts`:',
    '- Uses **Multer** with memory storage and a 50MB limit.',
    '- Validates MIME types: `image/jpeg`, `image/png`, `image/webp`, `video/mp4`.',
    '- Checks magic bytes to prevent spoofing (JPEG=`FFD8FF`, PNG=`89504E47`, WebP=`RIFF+WEBP`, MP4=`ftyp`).',
    '- Generates a SHA-256 hash.',
    '- Prevents path traversal and writes securely to the `uploads/` directory.',
    '',
    '## Audit Events',
    'All critical actions record an entry in the `auditEvents` table. These include actor ID, entity type/ID, action, and JSON metadata.'
  ].join('\n'));

  write('08-domain/priority-engine.md', [
    '# Priority Engine',
    '',
    '<span className="badge-implemented">Implemented</span>',
    '',
    '## Scoring Formula',
    'The Priority Engine (`lib/priority.ts`) calculates a dynamic score based on multiple factors:',
    '`Score = round(0.30 * S + 0.25 * C + 0.20 * E + 0.15 * U + 0.10 * (confidence * 100))`',
    '',
    '### Factors',
    '- **S (Severity)**: destroyed=100, severe=75, moderate=45, uncertain=35, minor=20, no_damage=0',
    '- **C (Criticality)**: hospital/emergency=100, bridge=85, gov/utility=75, school=70, residential=40, commercial=30, default=15',
    '- **E (Exposure)**: high=90, medium=55, low=20',
    '- **U (Urgency)**: `min(100, max(0, 100 - (hours/72)*100) + (accessConstrained ? 20 : 0))`',
    '',
    '## Return Value',
    'The engine returns an object containing the final score and a detailed breakdown:',
    '```typescript',
    '{',
    '  score: number,',
    '  breakdown: Array<{ label: string, value: number }>',
    '}',
    '```',
    '',
    '## Canonical Test',
    'Input: Severe severity, Hospital criticality, High exposure, 28.8h since event, access constrained, 0.55 confidence.',
    'Output: Final score `83`.'
  ].join('\n'));
}
